In [9]:
import pandas as pd 
import numpy as np 
from sklearn import linear_model
from sklearn.cross_validation import train_test_split

In [10]:
from sklearn.datasets import load_boston
boston = load_boston()

In [11]:
boston

{'DESCR': "Boston House Prices dataset\n===========================\n\nNotes\n------\nData Set Characteristics:  \n\n    :Number of Instances: 506 \n\n    :Number of Attributes: 13 numeric/categorical predictive\n    \n    :Median Value (attribute 14) is usually the target\n\n    :Attribute Information (in order):\n        - CRIM     per capita crime rate by town\n        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.\n        - INDUS    proportion of non-retail business acres per town\n        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)\n        - NOX      nitric oxides concentration (parts per 10 million)\n        - RM       average number of rooms per dwelling\n        - AGE      proportion of owner-occupied units built prior to 1940\n        - DIS      weighted distances to five Boston employment centres\n        - RAD      index of accessibility to radial highways\n        - TAX      full-value property-tax rate per

In [12]:
df_x=pd.DataFrame(boston.data,columns=boston.feature_names)

In [13]:
df_y=pd.DataFrame(boston.target)

In [14]:
df_x.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [15]:
df_x.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527  0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076  0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959  0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741  0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88

In [17]:
df_x.index

RangeIndex(start=0, stop=506, step=1)

In [19]:
df_x.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [20]:
df_x.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT'],
      dtype='object')

In [22]:
print(df_x.columns.values)

['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']


In [23]:
df_x.values

array([[  6.32000000e-03,   1.80000000e+01,   2.31000000e+00, ...,
          1.53000000e+01,   3.96900000e+02,   4.98000000e+00],
       [  2.73100000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          1.78000000e+01,   3.96900000e+02,   9.14000000e+00],
       [  2.72900000e-02,   0.00000000e+00,   7.07000000e+00, ...,
          1.78000000e+01,   3.92830000e+02,   4.03000000e+00],
       ..., 
       [  6.07600000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.96900000e+02,   5.64000000e+00],
       [  1.09590000e-01,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.93450000e+02,   6.48000000e+00],
       [  4.74100000e-02,   0.00000000e+00,   1.19300000e+01, ...,
          2.10000000e+01,   3.96900000e+02,   7.88000000e+00]])

In [24]:
df_x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13)
memory usage: 51.5 KB


In [25]:
df_x.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.593761   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.596783   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.647423   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [29]:
df_x.iloc[3:5,0:2]

CRIM   ZN
3  0.03237  0.0
4  0.06905  0.0

In [30]:
#Showing label slicing, both endpoints are included
df_x.loc[1:2,['CRIM','ZN']]

CRIM   ZN
1  0.02731  0.0
2  0.02729  0.0

In [31]:
df_x.loc[:,['NOX','AGE']]

NOX    AGE
0    0.538   65.2
1    0.469   78.9
2    0.469   61.1
3    0.458   45.8
4    0.458   54.2
5    0.458   58.7
6    0.524   66.6
7    0.524   96.1
8    0.524  100.0
9    0.524   85.9
10   0.524   94.3
11   0.524   82.9
12   0.524   39.0
13   0.538   61.8
14   0.538   84.5
15   0.538   56.5
16   0.538   29.3
17   0.538   81.7
18   0.538   36.6
19   0.538   69.5
20   0.538   98.1
21   0.538   89.2
22   0.538   91.7
23   0.538  100.0
24   0.538   94.1
25   0.538   85.7
26   0.538   90.3
27   0.538   88.8
28   0.538   94.4
29   0.538   87.3
..     ...    ...
476  0.614   93.6
477  0.614   97.3
478  0.614   96.7
479  0.614   88.0
480  0.532   64.7
481  0.532   74.9
482  0.532   77.0
483  0.532   40.3
484  0.583   41.9
485  0.583   51.9
486  0.583   79.8
487  0.583   53.2
488  0.609   92.7
489  0.609   98.3
490  0.609   98.0
491  0.609   98.8
492  0.609   83.5
493  0.585   54.0
494  0.585   42.6
495  0.585   28.8
496  0.585   72.9
497  0.585   70.6
498  0.585   65.3
499  0.585   73.5
500  0.585   79.7
501  0.573   69.1
502  0.573   76.7
503  0.573   91.0
504  0.573   89.3
505  0.573   80.8

[506 rows x 2 columns]

In [32]:
reg = linear_model.LinearRegression()

In [33]:
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)

In [34]:
x_train.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
192  0.08664  45.0   3.44   0.0  0.437  7.178  26.3  6.4798  5.0  398.0   
138  0.24980   0.0  21.89   0.0  0.624  5.857  98.2  1.6686  4.0  437.0   
251  0.21409  22.0   5.86   0.0  0.431  6.438   8.9  7.3967  7.0  330.0   
13   0.62976   0.0   8.14   0.0  0.538  5.949  61.8  4.7075  4.0  307.0   
256  0.01538  90.0   3.75   0.0  0.394  7.454  34.2  6.3361  3.0  244.0   

     PTRATIO       B  LSTAT  
192     15.2  390.49   2.87  
138     21.2  392.04  21.32  
251     19.1  377.07   3.59  
13      21.0  396.90   8.26  
256     15.9  386.34   3.11

In [35]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [36]:
reg.coef_

array([[ -1.14743504e-01,   4.70875035e-02,   8.70282354e-03,
          3.23818824e+00,  -1.67240567e+01,   3.87662996e+00,
         -1.08218769e-02,  -1.54144627e+00,   2.92604151e-01,
         -1.33989537e-02,  -9.07306805e-01,   8.91271054e-03,
         -4.58747039e-01]])

In [40]:
reg.predict(x_train)

array([[ 32.49024381],
       [ 14.19376591],
       [ 24.92818892],
       [ 19.49291568],
       [ 37.24118204],
       [ 31.71925187],
       [ 34.63037003],
       [ 28.84717207],
       [ 29.84998713],
       [ 20.53660692],
       [ 12.96539815],
       [ 29.89984474],
       [ 36.04738715],
       [ 22.81427586],
       [ 41.50242456],
       [ 17.72998846],
       [  4.13896717],
       [ 18.24324664],
       [ 22.6864545 ],
       [ 16.11814782],
       [ 28.41285382],
       [ 28.99351456],
       [ 19.37100874],
       [ 18.09274863],
       [ 36.2879701 ],
       [ 13.41429329],
       [ 14.56232734],
       [ 17.49607426],
       [ 39.35251987],
       [ 15.79600616],
       [ 42.96975122],
       [ 30.76656111],
       [ 29.84726751],
       [ 23.0325671 ],
       [ 13.41111627],
       [ 26.07241898],
       [ 23.12196865],
       [ 18.67448382],
       [ 15.84988499],
       [ 17.82308831],
       [ 21.07555152],
       [ 24.6933408 ],
       [  1.56327191],
       [ 22

In [43]:
y_train

0
192  36.4
138  13.3
251  24.8
13   20.4
256  44.0
299  29.0
180  39.8
92   22.9
219  23.0
152  15.3
214  23.7
191  30.5
276  33.2
184  26.4
163  50.0
421  14.2
490   8.1
61   16.0
76   20.0
397   8.5
238  23.7
302  26.4
323  18.5
459  20.0
166  50.0
423  13.4
33   13.1
394  12.7
225  50.0
24   15.6
..    ...
149  15.4
21   19.6
183  32.5
0    24.0
387   7.4
52   25.0
126  15.7
294  21.7
44   21.2
434  11.7
164  22.7
500  16.8
313  21.6
503  23.9
311  22.1
94   20.6
109  19.4
359  22.6
252  29.6
58   23.3
393  13.8
306  33.4
456  12.7
87   22.2
360  25.0
385   7.2
197  30.3
439  12.8
174  22.6
122  20.5

[404 rows x 1 columns]

In [37]:
reg.predict(x_test)

array([[ 12.06508881],
       [ 26.98544801],
       [ 17.59242607],
       [ 18.15842166],
       [ 36.91656975],
       [ 25.43573299],
       [ 31.08610267],
       [ 19.7198111 ],
       [ 19.63707329],
       [ 22.95805783],
       [ 28.38566642],
       [ 28.49200286],
       [ 19.00260488],
       [ 32.42578552],
       [ 21.52409329],
       [ 15.20850151],
       [ 21.23763462],
       [ 11.60093062],
       [ 11.38018796],
       [ 13.62527521],
       [  5.65831897],
       [ 17.34095216],
       [ 20.81305124],
       [ 22.51181212],
       [ 16.39301984],
       [ 20.32279223],
       [ 17.89495414],
       [ 14.23685883],
       [ 21.08606151],
       [ 17.50432715],
       [ 14.50006271],
       [ 23.63998403],
       [ 34.31768468],
       [ 22.23613308],
       [ 16.82042372],
       [ 20.15196012],
       [ 30.67786122],
       [ 35.60991076],
       [ 23.50419347],
       [ 24.67227487],
       [ 36.91121083],
       [ 32.34217047],
       [ 19.10793629],
       [ 32

In [51]:

#mean square error 
print(np.mean((reg.predict(x_test) - y_test)**2))

#mean absolute error 
print(np.mean(abs((reg.predict(x_test) - y_test))))

print(reg.score(x_train, y_train))
print(reg.score(x_test, y_test))



0    25.407977
dtype: float64
0    3.366331
dtype: float64
0.741450239507
0.726470137968


In [7]:
# Cross Validation Regression MAE
import pandas
from sklearn import cross_validation
from sklearn.linear_model import LinearRegression
url = "https://goo.gl/sXleFv"
names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO',
'B', 'LSTAT', 'MEDV']
dataframe = pandas.read_csv(url, delim_whitespace=True, names=names)
array = dataframe.values
X = array[:,0:13]
Y = array[:,13]
num_folds = 10
num_instances = len(X)
seed = 7
kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
model = LinearRegression()
scoring = 'mean_absolute_error'
results = cross_validation.cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("MAE: {0} ({1})".format(results.mean(), results.std()))

scoring = 'mean_squared_error'
results = cross_validation.cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("MSE: {0} ({1})".format(results.mean(), results.std()))

print("RMSE: {0} ({1})".format(results.mean(), results.std()))

sqrt = abs(results.mean())**(1/2.0)
print("RMSE: {0}".format(sqrt))

scoring = 'r2'
results = cross_validation.cross_val_score(model, X, Y, cv=kfold, scoring=scoring)
print("R^2: {0} ({1})".format(results.mean(), results.std()))

MAE: -4.004946635323951 (2.0835992687095755)
MSE: -34.705255944524446 (45.57399920030799)
RMSE: -34.705255944524446 (45.57399920030799)
RMSE: 5.891116697581575
R^2: 0.2025289900605598 (0.5952960169512658)


C:\Users\mohamed.noordeen\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:90: DeprecationWarning: Scoring method mean_absolute_error was renamed to neg_mean_absolute_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\mohamed.noordeen\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:90: DeprecationWarning: Scoring method mean_absolute_error was renamed to neg_mean_absolute_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\mohamed.noordeen\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:90: DeprecationWarning: Scoring method mean_absolute_error was renamed to neg_mean_absolute_error in version 0.18 and will be removed in 0.20.
  sample_weight=sample_weight)
C:\Users\mohamed.noordeen\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\metrics\scorer.py:90: DeprecationWarning: Scoring method mean_absolute_error was